export const SUPERADMIN_ROLE = 'SPE_SUPERADMIN'
export const HDAB_STAFF_ROLE = 'HDAB_STAFF'
export const HDAB_PERMIT_MANAGER_ROLE = 'HDAB_PERMIT_MANAGER'
export const HDAB_DATA_PREPARATOR_ROLE = 'HDAB_DATA_PREPARATOR'
export const HDAB_DATA_REVIEWER_ROLE = 'HDAB_DATA_REVIEWER'
export const HDAB_SETUP_ENGINEER_ROLE = 'HDAB_SETUP_ENGINEER'
export const HDAB_SETUP_REVIEWER_ROLE = 'HDAB_SETUP_REVIEWER'
export const HDAB_EGRESS_REVIEWER_ROLE = 'HDAB_EGRESS_REVIEWER'
export const DATA_HOLDER_ROLE = 'DATA_HOLDER'
export const DATA_HOLDER_GLOBAL_ROLE = 'DATA_HOLDER_USER'
export const PROJECT_INVESTIGATOR_ROLE = 'PROJECT_INVESTIGATOR'
export const PROJECT_MEMBER_ROLE = 'PROJECT_MEMBER'
export const PROJECT_ANONYMOUS_REVIEWER_ROLE = 'PROJECT_ANONYMOUS_REVIEWER'

export const HDAB_PERMIT_ROLES = [
  HDAB_DATA_PREPARATOR_ROLE,
  HDAB_DATA_REVIEWER_ROLE,
  HDAB_SETUP_ENGINEER_ROLE,
  HDAB_SETUP_REVIEWER_ROLE,
  HDAB_EGRESS_REVIEWER_ROLE,
] as const

export const PROJECT_CONTRIBUTOR_ROLES = [
  PROJECT_INVESTIGATOR_ROLE,
  PROJECT_MEMBER_ROLE,
] as const

export type HdabPermitRole = (typeof HDAB_PERMIT_ROLES)[number]
export type ProjectRole =
  | typeof PROJECT_INVESTIGATOR_ROLE
  | typeof PROJECT_MEMBER_ROLE
  | typeof PROJECT_ANONYMOUS_REVIEWER_ROLE
