export type PermitStatus =
  | 'AWAITING_INGRESS'
  | 'INGRESS_IN_PROGRESS'
  | 'DATA_PREPARATION_PENDING'
  | 'DATA_PREPARATION_REVIEW_PENDING'
  | 'DATA_PREPARATION_REWORK'
  | 'WORKSPACE_SETUP_PENDING'
  | 'WORKSPACE_SETUP_REVIEW_PENDING'
  | 'WORKSPACE_SETUP_REWORK'
  | 'ANALYSIS_ACTIVE'
  | 'EGRESS_REVIEW_PENDING'
  | 'EGRESS_REWORK'
  | 'EGRESS_APPROVED'
  | string

export type OutputStatus =
  | 'EGRESS_REVIEW_PENDING'
  | 'EGRESS_REWORK'
  | 'EGRESS_APPROVED'
  | string

export type ReviewDecision = 'APPROVED' | 'REWORK_REQUESTED' | 'SUBMIT_FOR_REVIEW'

export type ReviewStage = 'PREPARATION' | 'SETUP'
